### ISSUE TITLE
DTLS interrupted session at handshake do not get purged (or very late)

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [ARMmbed/coap-service#104]
There is an operator precedence error at https://github.com/ARMmbed/coap-service/blob/master/source/coap_service_api.c#L206 :

`if(coap_ticks && !coap_ticks % SECURE_SESSION_CLEAN_INTERVAL){`
should be
`if(coap_ticks && !(coap_ticks % SECURE_SESSION_CLEAN_INTERVAL)){`

The symptom is that coap_connection_handler_exec which is supposed to clean timed out sessions from the list never gets called.

**Comment by markus-becker-tridonic-com** [comment]
FYI: @MarceloSalazar @karsev

**Comment by markus-becker-tridonic-com** [comment]
Also you should be using `ns_list_foreach_safe` instead of `ns_list_foreach` when removing an item from the list, or?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-2905

**Comment by terhei** [comment]
Hi,

This issue have been fixed in PR: https://github.com/ARMmbed/coap-service/pull/105 and is now merged to master branch.
