### ISSUE TITLE
Redefinition of Mbed TLS error codes

### ISSUE THREAD

**Issue by SeppoTakalo** [ARMmbed/coap-service#75]
This module redefines MbedTLS macros when it detects unsecure platform.
https://github.com/ARMmbed/coap-service/blob/master/source/include/coap_security_handler.h#L104

This breaks the IAR build of [mbed-os-example-mesh-minimal](https://github.com/ARMmbed/mbed-os-example-mesh-minimal)

Please see: https://github.com/ARMmbed/mbed-os-example-mesh-minimal/issues/91

it might break other toolchains also.

**Comment by SeppoTakalo** [comment]
This seems to cause compilation warnings on GCC and ARM compiler. Causes build failure on IAR.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1996

**Comment by SeppoTakalo** [comment]
@terhei Please check.

**Comment by artokin** [comment]
PR in review: https://github.com/ARMmbed/mbed-os/pull/5138

**Comment by artokin** [comment]
PR is merged to mbed-os master and the PR is tagged for mbed-os-5.6.1.
Closing this issue.
