### ISSUE TITLE
Thread commisioning fails with Android application

### ISSUE THREAD

**Issue by artokin** [ARMmbed/coap-service#88]
Thread commissioning does not work when using Android commissioning application v1.01.11.

The application finds Thread border router but it is not able to connect it. 

Steps to reproduce:
1. Build nanostack-border-router application with the latest mbed-os (5.7.2)
1. Connect nanostack-border-router to IPv6 WiFi network
1. Connect Android device to the same WiFi network
1. Start Android commissioning application, the application finds nanostack-border-router
1. Observe result:

Actual result:

- Android commissioning application jams to network selection screen. The application does not open QR-code scanning screen and therefore no new devices can be added to the Thread network.

Expected result:

- Android commissioning application is able to connect to Thread network. QR-code scanning screen is opened and new devices can be added to the Thread network.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-2312

**Comment by terhei** [comment]
Issue fixed in PR's:
https://github.com/ARMmbed/coap-service/pull/87
https://github.com/ARMmbed/coap-service/pull/89
