### ISSUE TITLE
Thread Commissioning fails when using external commissioner

### ISSUE THREAD

**Issue by deepakvenugopal** [ARMmbed/coap-service#96]
Thread commission petition (c/cp) CoAP message does not get forwarded from Ethernet interface to Mesh. This prevents external commissioner from commissioning thread devices.

**Comment by deepakvenugopal** [comment]
https://github.com/ARMmbed/coap-service/pull/95 fixes this by reverting commit that caused this failure.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-2483

**Comment by deepakvenugopal** [comment]
Fixed in: https://github.com/ARMmbed/coap-service/pull/95
Fix delivered to mbed-os in: https://github.com/ARMmbed/mbed-os/pull/6251
