### ISSUE TITLE
What do I need to run a CoAP application using this library?

### ISSUE THREAD

**Issue by bsmelo** [ARMmbed/coap-service#97]
Hello,

I'm sorry if this is not the appropriate channel for this kind of question---I couldn't find any other.
Is there any example of a CoAP application server, based on this library, in which I can see the steps it performs until it finally listens on a given UDP port? And, most importantly, an application to which I could send, for instance a CoAP GET request using libcoap client and see that application handle such a request?

Thanks!
Bruno Melo.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-2491

**Comment by TuomoHautamaki** [comment]
I believe this is being discussed already via https://github.com/ARMmbed/mbed-coap/issues/49
Thus closing as duplicate. Please re-open if I misunderstood.
